Swiper
Popov-Maxim/Padabajka pull request #29
Opened 2024-04-07 09:48 UTC by Popov-Maxim

2024-04-10 16:18 UTC, awds333 requested changes

2024-04-10 16:18 UTC, awds333 commented on feature/swiper/src/commonMain/kotlin/com/fp/padabajka/feature/swiper/data/CardRepositoryImpl.kt
> +                    val nativeAd = nativeAdRepository.loadNextAd()
withTimeoutOrNull(10.seconds) {
    nativeAdRepository.loadNextAd()
}

2024-04-10 17:17 UTC, Popov-Maxim commented on feature/swiper/src/commonMain/kotlin/com/fp/padabajka/feature/swiper/data/CardRepositoryImpl.kt
> +                if (index != 0 && (index % AD_NUMBER - 1) == 0) {
не, я тут тупанул,
должно быть 
`index % (AD_NUMBER - 1) == 0`

2024-04-10 17:25 UTC, Popov-Maxim commented on feature/swiper/src/commonMain/kotlin/com/fp/padabajka/feature/swiper/data/CardRepositoryImpl.kt
> +                if (index != 0 && (index % AD_NUMBER - 1) == 0) {
поправил

2024-04-11 15:13 UTC, awds333 approved these changes

2024-04-11 16:26 UTC, merged